// Code generated by go-swagger; DO NOT EDIT.

package certificates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCSRsParams creates a new GetCSRsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCSRsParams() *GetCSRsParams {
	return &GetCSRsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCSRsParamsWithTimeout creates a new GetCSRsParams object
// with the ability to set a timeout on a request.
func NewGetCSRsParamsWithTimeout(timeout time.Duration) *GetCSRsParams {
	return &GetCSRsParams{
		timeout: timeout,
	}
}

// NewGetCSRsParamsWithContext creates a new GetCSRsParams object
// with the ability to set a context for a request.
func NewGetCSRsParamsWithContext(ctx context.Context) *GetCSRsParams {
	return &GetCSRsParams{
		Context: ctx,
	}
}

// NewGetCSRsParamsWithHTTPClient creates a new GetCSRsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCSRsParamsWithHTTPClient(client *http.Client) *GetCSRsParams {
	return &GetCSRsParams{
		HTTPClient: client,
	}
}

/*
GetCSRsParams contains all the parameters to send to the API endpoint

	for the get c s rs operation.

	Typically these are written to a http.Request.
*/
type GetCSRsParams struct {

	/* DomainName.

	   The domain name
	*/
	DomainName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get c s rs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCSRsParams) WithDefaults() *GetCSRsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get c s rs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCSRsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get c s rs params
func (o *GetCSRsParams) WithTimeout(timeout time.Duration) *GetCSRsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get c s rs params
func (o *GetCSRsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get c s rs params
func (o *GetCSRsParams) WithContext(ctx context.Context) *GetCSRsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get c s rs params
func (o *GetCSRsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get c s rs params
func (o *GetCSRsParams) WithHTTPClient(client *http.Client) *GetCSRsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get c s rs params
func (o *GetCSRsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomainName adds the domainName to the get c s rs params
func (o *GetCSRsParams) WithDomainName(domainName string) *GetCSRsParams {
	o.SetDomainName(domainName)
	return o
}

// SetDomainName adds the domainName to the get c s rs params
func (o *GetCSRsParams) SetDomainName(domainName string) {
	o.DomainName = domainName
}

// WriteToRequest writes these params to a swagger request
func (o *GetCSRsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param domainName
	if err := r.SetPathParam("domainName", o.DomainName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
