// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 VMware, Inc.
// SPDX-License-Identifier: BSD-2-Clause

package certificates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetResourceCertificatesValidationByIDParams creates a new GetResourceCertificatesValidationByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetResourceCertificatesValidationByIDParams() *GetResourceCertificatesValidationByIDParams {
	return &GetResourceCertificatesValidationByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetResourceCertificatesValidationByIDParamsWithTimeout creates a new GetResourceCertificatesValidationByIDParams object
// with the ability to set a timeout on a request.
func NewGetResourceCertificatesValidationByIDParamsWithTimeout(timeout time.Duration) *GetResourceCertificatesValidationByIDParams {
	return &GetResourceCertificatesValidationByIDParams{
		timeout: timeout,
	}
}

// NewGetResourceCertificatesValidationByIDParamsWithContext creates a new GetResourceCertificatesValidationByIDParams object
// with the ability to set a context for a request.
func NewGetResourceCertificatesValidationByIDParamsWithContext(ctx context.Context) *GetResourceCertificatesValidationByIDParams {
	return &GetResourceCertificatesValidationByIDParams{
		Context: ctx,
	}
}

// NewGetResourceCertificatesValidationByIDParamsWithHTTPClient creates a new GetResourceCertificatesValidationByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetResourceCertificatesValidationByIDParamsWithHTTPClient(client *http.Client) *GetResourceCertificatesValidationByIDParams {
	return &GetResourceCertificatesValidationByIDParams{
		HTTPClient: client,
	}
}

/*
GetResourceCertificatesValidationByIDParams contains all the parameters to send to the API endpoint

	for the get resource certificates validation by ID operation.

	Typically these are written to a http.Request.
*/
type GetResourceCertificatesValidationByIDParams struct {

	/* ID.

	   Domain ID
	*/
	ID string

	/* ValidationID.

	   Validation ID
	*/
	ValidationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get resource certificates validation by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetResourceCertificatesValidationByIDParams) WithDefaults() *GetResourceCertificatesValidationByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get resource certificates validation by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetResourceCertificatesValidationByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get resource certificates validation by ID params
func (o *GetResourceCertificatesValidationByIDParams) WithTimeout(timeout time.Duration) *GetResourceCertificatesValidationByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get resource certificates validation by ID params
func (o *GetResourceCertificatesValidationByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get resource certificates validation by ID params
func (o *GetResourceCertificatesValidationByIDParams) WithContext(ctx context.Context) *GetResourceCertificatesValidationByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get resource certificates validation by ID params
func (o *GetResourceCertificatesValidationByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get resource certificates validation by ID params
func (o *GetResourceCertificatesValidationByIDParams) WithHTTPClient(client *http.Client) *GetResourceCertificatesValidationByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get resource certificates validation by ID params
func (o *GetResourceCertificatesValidationByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get resource certificates validation by ID params
func (o *GetResourceCertificatesValidationByIDParams) WithID(id string) *GetResourceCertificatesValidationByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get resource certificates validation by ID params
func (o *GetResourceCertificatesValidationByIDParams) SetID(id string) {
	o.ID = id
}

// WithValidationID adds the validationID to the get resource certificates validation by ID params
func (o *GetResourceCertificatesValidationByIDParams) WithValidationID(validationID string) *GetResourceCertificatesValidationByIDParams {
	o.SetValidationID(validationID)
	return o
}

// SetValidationID adds the validationId to the get resource certificates validation by ID params
func (o *GetResourceCertificatesValidationByIDParams) SetValidationID(validationID string) {
	o.ValidationID = validationID
}

// WriteToRequest writes these params to a swagger request
func (o *GetResourceCertificatesValidationByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param validationId
	if err := r.SetPathParam("validationId", o.ValidationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
