// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 VMware, Inc.
// SPDX-License-Identifier: BSD-2-Clause

package certificates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vcf-sdk-go/models"
)

// NewValidateResourceCertificatesParams creates a new ValidateResourceCertificatesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewValidateResourceCertificatesParams() *ValidateResourceCertificatesParams {
	return &ValidateResourceCertificatesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewValidateResourceCertificatesParamsWithTimeout creates a new ValidateResourceCertificatesParams object
// with the ability to set a timeout on a request.
func NewValidateResourceCertificatesParamsWithTimeout(timeout time.Duration) *ValidateResourceCertificatesParams {
	return &ValidateResourceCertificatesParams{
		timeout: timeout,
	}
}

// NewValidateResourceCertificatesParamsWithContext creates a new ValidateResourceCertificatesParams object
// with the ability to set a context for a request.
func NewValidateResourceCertificatesParamsWithContext(ctx context.Context) *ValidateResourceCertificatesParams {
	return &ValidateResourceCertificatesParams{
		Context: ctx,
	}
}

// NewValidateResourceCertificatesParamsWithHTTPClient creates a new ValidateResourceCertificatesParams object
// with the ability to set a custom HTTPClient for a request.
func NewValidateResourceCertificatesParamsWithHTTPClient(client *http.Client) *ValidateResourceCertificatesParams {
	return &ValidateResourceCertificatesParams{
		HTTPClient: client,
	}
}

/*
ValidateResourceCertificatesParams contains all the parameters to send to the API endpoint

	for the validate resource certificates operation.

	Typically these are written to a http.Request.
*/
type ValidateResourceCertificatesParams struct {

	/* ID.

	   Domain ID
	*/
	ID string

	/* ResourceCertificateSpecs.

	   resourceCertificateSpecs
	*/
	ResourceCertificateSpecs []*models.ResourceCertificateSpec

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the validate resource certificates params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ValidateResourceCertificatesParams) WithDefaults() *ValidateResourceCertificatesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the validate resource certificates params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ValidateResourceCertificatesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the validate resource certificates params
func (o *ValidateResourceCertificatesParams) WithTimeout(timeout time.Duration) *ValidateResourceCertificatesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the validate resource certificates params
func (o *ValidateResourceCertificatesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the validate resource certificates params
func (o *ValidateResourceCertificatesParams) WithContext(ctx context.Context) *ValidateResourceCertificatesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the validate resource certificates params
func (o *ValidateResourceCertificatesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the validate resource certificates params
func (o *ValidateResourceCertificatesParams) WithHTTPClient(client *http.Client) *ValidateResourceCertificatesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the validate resource certificates params
func (o *ValidateResourceCertificatesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the validate resource certificates params
func (o *ValidateResourceCertificatesParams) WithID(id string) *ValidateResourceCertificatesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the validate resource certificates params
func (o *ValidateResourceCertificatesParams) SetID(id string) {
	o.ID = id
}

// WithResourceCertificateSpecs adds the resourceCertificateSpecs to the validate resource certificates params
func (o *ValidateResourceCertificatesParams) WithResourceCertificateSpecs(resourceCertificateSpecs []*models.ResourceCertificateSpec) *ValidateResourceCertificatesParams {
	o.SetResourceCertificateSpecs(resourceCertificateSpecs)
	return o
}

// SetResourceCertificateSpecs adds the resourceCertificateSpecs to the validate resource certificates params
func (o *ValidateResourceCertificatesParams) SetResourceCertificateSpecs(resourceCertificateSpecs []*models.ResourceCertificateSpec) {
	o.ResourceCertificateSpecs = resourceCertificateSpecs
}

// WriteToRequest writes these params to a swagger request
func (o *ValidateResourceCertificatesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.ResourceCertificateSpecs != nil {
		if err := r.SetBodyParam(o.ResourceCertificateSpecs); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
