// Code generated by go-swagger; DO NOT EDIT.

// Copyright © 2023 VMware, Inc. All Rights Reserved.
// Code licenced under: BSD-2

package proxy_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"vcf-sdk-go/models"
)

// GETProxyConfigurationReader is a Reader for the GETProxyConfiguration structure.
type GETProxyConfigurationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETProxyConfigurationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGETProxyConfigurationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGETProxyConfigurationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGETProxyConfigurationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGETProxyConfigurationOK creates a GETProxyConfigurationOK with default headers values
func NewGETProxyConfigurationOK() *GETProxyConfigurationOK {
	return &GETProxyConfigurationOK{}
}

/*
GETProxyConfigurationOK describes a response with status code 200, with default header values.

OK
*/
type GETProxyConfigurationOK struct {
	Payload *models.ProxyConfiguration
}

// IsSuccess returns true when this get proxy configuration o k response has a 2xx status code
func (o *GETProxyConfigurationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get proxy configuration o k response has a 3xx status code
func (o *GETProxyConfigurationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get proxy configuration o k response has a 4xx status code
func (o *GETProxyConfigurationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get proxy configuration o k response has a 5xx status code
func (o *GETProxyConfigurationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get proxy configuration o k response a status code equal to that given
func (o *GETProxyConfigurationOK) IsCode(code int) bool {
	return code == 200
}

func (o *GETProxyConfigurationOK) Error() string {
	return fmt.Sprintf("[GET /v1/system/proxy-configuration][%d] getProxyConfigurationOK  %+v", 200, o.Payload)
}

func (o *GETProxyConfigurationOK) String() string {
	return fmt.Sprintf("[GET /v1/system/proxy-configuration][%d] getProxyConfigurationOK  %+v", 200, o.Payload)
}

func (o *GETProxyConfigurationOK) GetPayload() *models.ProxyConfiguration {
	return o.Payload
}

func (o *GETProxyConfigurationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProxyConfiguration)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETProxyConfigurationBadRequest creates a GETProxyConfigurationBadRequest with default headers values
func NewGETProxyConfigurationBadRequest() *GETProxyConfigurationBadRequest {
	return &GETProxyConfigurationBadRequest{}
}

/*
GETProxyConfigurationBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GETProxyConfigurationBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get proxy configuration bad request response has a 2xx status code
func (o *GETProxyConfigurationBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get proxy configuration bad request response has a 3xx status code
func (o *GETProxyConfigurationBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get proxy configuration bad request response has a 4xx status code
func (o *GETProxyConfigurationBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get proxy configuration bad request response has a 5xx status code
func (o *GETProxyConfigurationBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get proxy configuration bad request response a status code equal to that given
func (o *GETProxyConfigurationBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GETProxyConfigurationBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/system/proxy-configuration][%d] getProxyConfigurationBadRequest  %+v", 400, o.Payload)
}

func (o *GETProxyConfigurationBadRequest) String() string {
	return fmt.Sprintf("[GET /v1/system/proxy-configuration][%d] getProxyConfigurationBadRequest  %+v", 400, o.Payload)
}

func (o *GETProxyConfigurationBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GETProxyConfigurationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETProxyConfigurationInternalServerError creates a GETProxyConfigurationInternalServerError with default headers values
func NewGETProxyConfigurationInternalServerError() *GETProxyConfigurationInternalServerError {
	return &GETProxyConfigurationInternalServerError{}
}

/*
GETProxyConfigurationInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GETProxyConfigurationInternalServerError struct {
}

// IsSuccess returns true when this get proxy configuration internal server error response has a 2xx status code
func (o *GETProxyConfigurationInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get proxy configuration internal server error response has a 3xx status code
func (o *GETProxyConfigurationInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get proxy configuration internal server error response has a 4xx status code
func (o *GETProxyConfigurationInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get proxy configuration internal server error response has a 5xx status code
func (o *GETProxyConfigurationInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get proxy configuration internal server error response a status code equal to that given
func (o *GETProxyConfigurationInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GETProxyConfigurationInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/system/proxy-configuration][%d] getProxyConfigurationInternalServerError ", 500)
}

func (o *GETProxyConfigurationInternalServerError) String() string {
	return fmt.Sprintf("[GET /v1/system/proxy-configuration][%d] getProxyConfigurationInternalServerError ", 500)
}

func (o *GETProxyConfigurationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
