// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 VMware, Inc.
// SPDX-License-Identifier: BSD-2-Clause

package network_pools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetNetworkPoolParams creates a new GetNetworkPoolParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetNetworkPoolParams() *GetNetworkPoolParams {
	return &GetNetworkPoolParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetNetworkPoolParamsWithTimeout creates a new GetNetworkPoolParams object
// with the ability to set a timeout on a request.
func NewGetNetworkPoolParamsWithTimeout(timeout time.Duration) *GetNetworkPoolParams {
	return &GetNetworkPoolParams{
		timeout: timeout,
	}
}

// NewGetNetworkPoolParamsWithContext creates a new GetNetworkPoolParams object
// with the ability to set a context for a request.
func NewGetNetworkPoolParamsWithContext(ctx context.Context) *GetNetworkPoolParams {
	return &GetNetworkPoolParams{
		Context: ctx,
	}
}

// NewGetNetworkPoolParamsWithHTTPClient creates a new GetNetworkPoolParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetNetworkPoolParamsWithHTTPClient(client *http.Client) *GetNetworkPoolParams {
	return &GetNetworkPoolParams{
		HTTPClient: client,
	}
}

/*
GetNetworkPoolParams contains all the parameters to send to the API endpoint

	for the get network pool operation.

	Typically these are written to a http.Request.
*/
type GetNetworkPoolParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get network pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNetworkPoolParams) WithDefaults() *GetNetworkPoolParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get network pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNetworkPoolParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get network pool params
func (o *GetNetworkPoolParams) WithTimeout(timeout time.Duration) *GetNetworkPoolParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get network pool params
func (o *GetNetworkPoolParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get network pool params
func (o *GetNetworkPoolParams) WithContext(ctx context.Context) *GetNetworkPoolParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get network pool params
func (o *GetNetworkPoolParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get network pool params
func (o *GetNetworkPoolParams) WithHTTPClient(client *http.Client) *GetNetworkPoolParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get network pool params
func (o *GetNetworkPoolParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetNetworkPoolParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
