---
chore:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
          - .gitignore
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - **/*.md
github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**/*
needs-review:
  - changed-files:
      - any-glob-to-any-file:
          - **
sdk:
  - changed-files:
      - any-glob-to-any-file:
          - client/**/*
          - models/**/*
          - scripts/**/*
