// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 VMware, Inc.
// SPDX-License-Identifier: BSD-2-Clause

package check_sets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vcf-sdk-go/models"
)

// NewTriggerPartialRetryOfCheckRunParams creates a new TriggerPartialRetryOfCheckRunParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTriggerPartialRetryOfCheckRunParams() *TriggerPartialRetryOfCheckRunParams {
	return &TriggerPartialRetryOfCheckRunParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTriggerPartialRetryOfCheckRunParamsWithTimeout creates a new TriggerPartialRetryOfCheckRunParams object
// with the ability to set a timeout on a request.
func NewTriggerPartialRetryOfCheckRunParamsWithTimeout(timeout time.Duration) *TriggerPartialRetryOfCheckRunParams {
	return &TriggerPartialRetryOfCheckRunParams{
		timeout: timeout,
	}
}

// NewTriggerPartialRetryOfCheckRunParamsWithContext creates a new TriggerPartialRetryOfCheckRunParams object
// with the ability to set a context for a request.
func NewTriggerPartialRetryOfCheckRunParamsWithContext(ctx context.Context) *TriggerPartialRetryOfCheckRunParams {
	return &TriggerPartialRetryOfCheckRunParams{
		Context: ctx,
	}
}

// NewTriggerPartialRetryOfCheckRunParamsWithHTTPClient creates a new TriggerPartialRetryOfCheckRunParams object
// with the ability to set a custom HTTPClient for a request.
func NewTriggerPartialRetryOfCheckRunParamsWithHTTPClient(client *http.Client) *TriggerPartialRetryOfCheckRunParams {
	return &TriggerPartialRetryOfCheckRunParams{
		HTTPClient: client,
	}
}

/*
TriggerPartialRetryOfCheckRunParams contains all the parameters to send to the API endpoint

	for the trigger partial retry of check run operation.

	Typically these are written to a http.Request.
*/
type TriggerPartialRetryOfCheckRunParams struct {

	/* AssessmentPartialRetryInputRest.

	   Spec for assessment retry
	*/
	AssessmentPartialRetryInputRest *models.AssessmentPartialRetryInput

	/* RunID.

	   UUID of the assessment to retry
	*/
	RunID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the trigger partial retry of check run params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TriggerPartialRetryOfCheckRunParams) WithDefaults() *TriggerPartialRetryOfCheckRunParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the trigger partial retry of check run params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TriggerPartialRetryOfCheckRunParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the trigger partial retry of check run params
func (o *TriggerPartialRetryOfCheckRunParams) WithTimeout(timeout time.Duration) *TriggerPartialRetryOfCheckRunParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the trigger partial retry of check run params
func (o *TriggerPartialRetryOfCheckRunParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the trigger partial retry of check run params
func (o *TriggerPartialRetryOfCheckRunParams) WithContext(ctx context.Context) *TriggerPartialRetryOfCheckRunParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the trigger partial retry of check run params
func (o *TriggerPartialRetryOfCheckRunParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the trigger partial retry of check run params
func (o *TriggerPartialRetryOfCheckRunParams) WithHTTPClient(client *http.Client) *TriggerPartialRetryOfCheckRunParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the trigger partial retry of check run params
func (o *TriggerPartialRetryOfCheckRunParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAssessmentPartialRetryInputRest adds the assessmentPartialRetryInputRest to the trigger partial retry of check run params
func (o *TriggerPartialRetryOfCheckRunParams) WithAssessmentPartialRetryInputRest(assessmentPartialRetryInputRest *models.AssessmentPartialRetryInput) *TriggerPartialRetryOfCheckRunParams {
	o.SetAssessmentPartialRetryInputRest(assessmentPartialRetryInputRest)
	return o
}

// SetAssessmentPartialRetryInputRest adds the assessmentPartialRetryInputRest to the trigger partial retry of check run params
func (o *TriggerPartialRetryOfCheckRunParams) SetAssessmentPartialRetryInputRest(assessmentPartialRetryInputRest *models.AssessmentPartialRetryInput) {
	o.AssessmentPartialRetryInputRest = assessmentPartialRetryInputRest
}

// WithRunID adds the runID to the trigger partial retry of check run params
func (o *TriggerPartialRetryOfCheckRunParams) WithRunID(runID string) *TriggerPartialRetryOfCheckRunParams {
	o.SetRunID(runID)
	return o
}

// SetRunID adds the runId to the trigger partial retry of check run params
func (o *TriggerPartialRetryOfCheckRunParams) SetRunID(runID string) {
	o.RunID = runID
}

// WriteToRequest writes these params to a swagger request
func (o *TriggerPartialRetryOfCheckRunParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.AssessmentPartialRetryInputRest != nil {
		if err := r.SetBodyParam(o.AssessmentPartialRetryInputRest); err != nil {
			return err
		}
	}

	// path param runId
	if err := r.SetPathParam("runId", o.RunID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
