// Code generated by go-swagger; DO NOT EDIT.

package c_e_ip

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCeipStatusParams creates a new GetCeipStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCeipStatusParams() *GetCeipStatusParams {
	return &GetCeipStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCeipStatusParamsWithTimeout creates a new GetCeipStatusParams object
// with the ability to set a timeout on a request.
func NewGetCeipStatusParamsWithTimeout(timeout time.Duration) *GetCeipStatusParams {
	return &GetCeipStatusParams{
		timeout: timeout,
	}
}

// NewGetCeipStatusParamsWithContext creates a new GetCeipStatusParams object
// with the ability to set a context for a request.
func NewGetCeipStatusParamsWithContext(ctx context.Context) *GetCeipStatusParams {
	return &GetCeipStatusParams{
		Context: ctx,
	}
}

// NewGetCeipStatusParamsWithHTTPClient creates a new GetCeipStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCeipStatusParamsWithHTTPClient(client *http.Client) *GetCeipStatusParams {
	return &GetCeipStatusParams{
		HTTPClient: client,
	}
}

/*
GetCeipStatusParams contains all the parameters to send to the API endpoint

	for the get ceip status operation.

	Typically these are written to a http.Request.
*/
type GetCeipStatusParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get ceip status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCeipStatusParams) WithDefaults() *GetCeipStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get ceip status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCeipStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get ceip status params
func (o *GetCeipStatusParams) WithTimeout(timeout time.Duration) *GetCeipStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get ceip status params
func (o *GetCeipStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get ceip status params
func (o *GetCeipStatusParams) WithContext(ctx context.Context) *GetCeipStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get ceip status params
func (o *GetCeipStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get ceip status params
func (o *GetCeipStatusParams) WithHTTPClient(client *http.Client) *GetCeipStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get ceip status params
func (o *GetCeipStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCeipStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
