// Code generated by go-swagger; DO NOT EDIT.

package sddc_managers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSddcManagerParams creates a new GetSddcManagerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSddcManagerParams() *GetSddcManagerParams {
	return &GetSddcManagerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSddcManagerParamsWithTimeout creates a new GetSddcManagerParams object
// with the ability to set a timeout on a request.
func NewGetSddcManagerParamsWithTimeout(timeout time.Duration) *GetSddcManagerParams {
	return &GetSddcManagerParams{
		timeout: timeout,
	}
}

// NewGetSddcManagerParamsWithContext creates a new GetSddcManagerParams object
// with the ability to set a context for a request.
func NewGetSddcManagerParamsWithContext(ctx context.Context) *GetSddcManagerParams {
	return &GetSddcManagerParams{
		Context: ctx,
	}
}

// NewGetSddcManagerParamsWithHTTPClient creates a new GetSddcManagerParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSddcManagerParamsWithHTTPClient(client *http.Client) *GetSddcManagerParams {
	return &GetSddcManagerParams{
		HTTPClient: client,
	}
}

/*
GetSddcManagerParams contains all the parameters to send to the API endpoint

	for the get sddc manager operation.

	Typically these are written to a http.Request.
*/
type GetSddcManagerParams struct {

	/* ID.

	   Sddc Manager ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get sddc manager params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSddcManagerParams) WithDefaults() *GetSddcManagerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get sddc manager params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSddcManagerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get sddc manager params
func (o *GetSddcManagerParams) WithTimeout(timeout time.Duration) *GetSddcManagerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get sddc manager params
func (o *GetSddcManagerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get sddc manager params
func (o *GetSddcManagerParams) WithContext(ctx context.Context) *GetSddcManagerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get sddc manager params
func (o *GetSddcManagerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get sddc manager params
func (o *GetSddcManagerParams) WithHTTPClient(client *http.Client) *GetSddcManagerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get sddc manager params
func (o *GetSddcManagerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get sddc manager params
func (o *GetSddcManagerParams) WithID(id string) *GetSddcManagerParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get sddc manager params
func (o *GetSddcManagerParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetSddcManagerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
