// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 VMware, Inc.
// SPDX-License-Identifier: BSD-2-Clause

package resource_warnings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vcf-sdk-go/models"
)

// GETResourceWarningReader is a Reader for the GETResourceWarning structure.
type GETResourceWarningReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETResourceWarningReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGETResourceWarningOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGETResourceWarningNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGETResourceWarningInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGETResourceWarningOK creates a GETResourceWarningOK with default headers values
func NewGETResourceWarningOK() *GETResourceWarningOK {
	return &GETResourceWarningOK{}
}

/*
GETResourceWarningOK describes a response with status code 200, with default header values.

OK
*/
type GETResourceWarningOK struct {
	Payload *models.ResourceWarning
}

// IsSuccess returns true when this get resource warning o k response has a 2xx status code
func (o *GETResourceWarningOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get resource warning o k response has a 3xx status code
func (o *GETResourceWarningOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get resource warning o k response has a 4xx status code
func (o *GETResourceWarningOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get resource warning o k response has a 5xx status code
func (o *GETResourceWarningOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get resource warning o k response a status code equal to that given
func (o *GETResourceWarningOK) IsCode(code int) bool {
	return code == 200
}

func (o *GETResourceWarningOK) Error() string {
	return fmt.Sprintf("[GET /v1/resource-warnings/{id}][%d] getResourceWarningOK  %+v", 200, o.Payload)
}

func (o *GETResourceWarningOK) String() string {
	return fmt.Sprintf("[GET /v1/resource-warnings/{id}][%d] getResourceWarningOK  %+v", 200, o.Payload)
}

func (o *GETResourceWarningOK) GetPayload() *models.ResourceWarning {
	return o.Payload
}

func (o *GETResourceWarningOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceWarning)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETResourceWarningNotFound creates a GETResourceWarningNotFound with default headers values
func NewGETResourceWarningNotFound() *GETResourceWarningNotFound {
	return &GETResourceWarningNotFound{}
}

/*
GETResourceWarningNotFound describes a response with status code 404, with default header values.

Resource Warning not found
*/
type GETResourceWarningNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get resource warning not found response has a 2xx status code
func (o *GETResourceWarningNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get resource warning not found response has a 3xx status code
func (o *GETResourceWarningNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get resource warning not found response has a 4xx status code
func (o *GETResourceWarningNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get resource warning not found response has a 5xx status code
func (o *GETResourceWarningNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get resource warning not found response a status code equal to that given
func (o *GETResourceWarningNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GETResourceWarningNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/resource-warnings/{id}][%d] getResourceWarningNotFound  %+v", 404, o.Payload)
}

func (o *GETResourceWarningNotFound) String() string {
	return fmt.Sprintf("[GET /v1/resource-warnings/{id}][%d] getResourceWarningNotFound  %+v", 404, o.Payload)
}

func (o *GETResourceWarningNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GETResourceWarningNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETResourceWarningInternalServerError creates a GETResourceWarningInternalServerError with default headers values
func NewGETResourceWarningInternalServerError() *GETResourceWarningInternalServerError {
	return &GETResourceWarningInternalServerError{}
}

/*
GETResourceWarningInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GETResourceWarningInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get resource warning internal server error response has a 2xx status code
func (o *GETResourceWarningInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get resource warning internal server error response has a 3xx status code
func (o *GETResourceWarningInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get resource warning internal server error response has a 4xx status code
func (o *GETResourceWarningInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get resource warning internal server error response has a 5xx status code
func (o *GETResourceWarningInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get resource warning internal server error response a status code equal to that given
func (o *GETResourceWarningInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GETResourceWarningInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/resource-warnings/{id}][%d] getResourceWarningInternalServerError  %+v", 500, o.Payload)
}

func (o *GETResourceWarningInternalServerError) String() string {
	return fmt.Sprintf("[GET /v1/resource-warnings/{id}][%d] getResourceWarningInternalServerError  %+v", 500, o.Payload)
}

func (o *GETResourceWarningInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GETResourceWarningInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
