// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 VMware, Inc.
// SPDX-License-Identifier: BSD-2-Clause

package sos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vcf-sdk-go/models"
)

// NewStartHealthCheckParams creates a new StartHealthCheckParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStartHealthCheckParams() *StartHealthCheckParams {
	return &StartHealthCheckParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStartHealthCheckParamsWithTimeout creates a new StartHealthCheckParams object
// with the ability to set a timeout on a request.
func NewStartHealthCheckParamsWithTimeout(timeout time.Duration) *StartHealthCheckParams {
	return &StartHealthCheckParams{
		timeout: timeout,
	}
}

// NewStartHealthCheckParamsWithContext creates a new StartHealthCheckParams object
// with the ability to set a context for a request.
func NewStartHealthCheckParamsWithContext(ctx context.Context) *StartHealthCheckParams {
	return &StartHealthCheckParams{
		Context: ctx,
	}
}

// NewStartHealthCheckParamsWithHTTPClient creates a new StartHealthCheckParams object
// with the ability to set a custom HTTPClient for a request.
func NewStartHealthCheckParamsWithHTTPClient(client *http.Client) *StartHealthCheckParams {
	return &StartHealthCheckParams{
		HTTPClient: client,
	}
}

/*
StartHealthCheckParams contains all the parameters to send to the API endpoint

	for the start health check operation.

	Typically these are written to a http.Request.
*/
type StartHealthCheckParams struct {

	/* Healthsummaryspec.

	   healthsummaryspec
	*/
	Healthsummaryspec *models.HealthSummarySpec

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the start health check params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StartHealthCheckParams) WithDefaults() *StartHealthCheckParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the start health check params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StartHealthCheckParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the start health check params
func (o *StartHealthCheckParams) WithTimeout(timeout time.Duration) *StartHealthCheckParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the start health check params
func (o *StartHealthCheckParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the start health check params
func (o *StartHealthCheckParams) WithContext(ctx context.Context) *StartHealthCheckParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the start health check params
func (o *StartHealthCheckParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the start health check params
func (o *StartHealthCheckParams) WithHTTPClient(client *http.Client) *StartHealthCheckParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the start health check params
func (o *StartHealthCheckParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHealthsummaryspec adds the healthsummaryspec to the start health check params
func (o *StartHealthCheckParams) WithHealthsummaryspec(healthsummaryspec *models.HealthSummarySpec) *StartHealthCheckParams {
	o.SetHealthsummaryspec(healthsummaryspec)
	return o
}

// SetHealthsummaryspec adds the healthsummaryspec to the start health check params
func (o *StartHealthCheckParams) SetHealthsummaryspec(healthsummaryspec *models.HealthSummarySpec) {
	o.Healthsummaryspec = healthsummaryspec
}

// WriteToRequest writes these params to a swagger request
func (o *StartHealthCheckParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Healthsummaryspec != nil {
		if err := r.SetBodyParam(o.Healthsummaryspec); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
