// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 VMware, Inc.
// SPDX-License-Identifier: BSD-2-Clause

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSystemConfigurationParams creates a new GetSystemConfigurationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSystemConfigurationParams() *GetSystemConfigurationParams {
	return &GetSystemConfigurationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSystemConfigurationParamsWithTimeout creates a new GetSystemConfigurationParams object
// with the ability to set a timeout on a request.
func NewGetSystemConfigurationParamsWithTimeout(timeout time.Duration) *GetSystemConfigurationParams {
	return &GetSystemConfigurationParams{
		timeout: timeout,
	}
}

// NewGetSystemConfigurationParamsWithContext creates a new GetSystemConfigurationParams object
// with the ability to set a context for a request.
func NewGetSystemConfigurationParamsWithContext(ctx context.Context) *GetSystemConfigurationParams {
	return &GetSystemConfigurationParams{
		Context: ctx,
	}
}

// NewGetSystemConfigurationParamsWithHTTPClient creates a new GetSystemConfigurationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSystemConfigurationParamsWithHTTPClient(client *http.Client) *GetSystemConfigurationParams {
	return &GetSystemConfigurationParams{
		HTTPClient: client,
	}
}

/*
GetSystemConfigurationParams contains all the parameters to send to the API endpoint

	for the get system configuration operation.

	Typically these are written to a http.Request.
*/
type GetSystemConfigurationParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get system configuration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSystemConfigurationParams) WithDefaults() *GetSystemConfigurationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get system configuration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSystemConfigurationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get system configuration params
func (o *GetSystemConfigurationParams) WithTimeout(timeout time.Duration) *GetSystemConfigurationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get system configuration params
func (o *GetSystemConfigurationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get system configuration params
func (o *GetSystemConfigurationParams) WithContext(ctx context.Context) *GetSystemConfigurationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get system configuration params
func (o *GetSystemConfigurationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get system configuration params
func (o *GetSystemConfigurationParams) WithHTTPClient(client *http.Client) *GetSystemConfigurationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get system configuration params
func (o *GetSystemConfigurationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSystemConfigurationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
