// Code generated by go-swagger; DO NOT EDIT.

// Copyright © 2023 VMware, Inc. All Rights Reserved.
// Code licenced under: BSD-2

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGETDomainTagManagerURLParams creates a new GETDomainTagManagerURLParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGETDomainTagManagerURLParams() *GETDomainTagManagerURLParams {
	return &GETDomainTagManagerURLParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGETDomainTagManagerURLParamsWithTimeout creates a new GETDomainTagManagerURLParams object
// with the ability to set a timeout on a request.
func NewGETDomainTagManagerURLParamsWithTimeout(timeout time.Duration) *GETDomainTagManagerURLParams {
	return &GETDomainTagManagerURLParams{
		timeout: timeout,
	}
}

// NewGETDomainTagManagerURLParamsWithContext creates a new GETDomainTagManagerURLParams object
// with the ability to set a context for a request.
func NewGETDomainTagManagerURLParamsWithContext(ctx context.Context) *GETDomainTagManagerURLParams {
	return &GETDomainTagManagerURLParams{
		Context: ctx,
	}
}

// NewGETDomainTagManagerURLParamsWithHTTPClient creates a new GETDomainTagManagerURLParams object
// with the ability to set a custom HTTPClient for a request.
func NewGETDomainTagManagerURLParamsWithHTTPClient(client *http.Client) *GETDomainTagManagerURLParams {
	return &GETDomainTagManagerURLParams{
		HTTPClient: client,
	}
}

/*
GETDomainTagManagerURLParams contains all the parameters to send to the API endpoint

	for the get domain tag manager Url operation.

	Typically these are written to a http.Request.
*/
type GETDomainTagManagerURLParams struct {

	/* ID.

	   Domain ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get domain tag manager Url params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GETDomainTagManagerURLParams) WithDefaults() *GETDomainTagManagerURLParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get domain tag manager Url params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GETDomainTagManagerURLParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get domain tag manager Url params
func (o *GETDomainTagManagerURLParams) WithTimeout(timeout time.Duration) *GETDomainTagManagerURLParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get domain tag manager Url params
func (o *GETDomainTagManagerURLParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get domain tag manager Url params
func (o *GETDomainTagManagerURLParams) WithContext(ctx context.Context) *GETDomainTagManagerURLParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get domain tag manager Url params
func (o *GETDomainTagManagerURLParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get domain tag manager Url params
func (o *GETDomainTagManagerURLParams) WithHTTPClient(client *http.Client) *GETDomainTagManagerURLParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get domain tag manager Url params
func (o *GETDomainTagManagerURLParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get domain tag manager Url params
func (o *GETDomainTagManagerURLParams) WithID(id string) *GETDomainTagManagerURLParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get domain tag manager Url params
func (o *GETDomainTagManagerURLParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GETDomainTagManagerURLParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
