// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 VMware, Inc.
// SPDX-License-Identifier: BSD-2-Clause

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGETDomainsParams creates a new GETDomainsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGETDomainsParams() *GETDomainsParams {
	return &GETDomainsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGETDomainsParamsWithTimeout creates a new GETDomainsParams object
// with the ability to set a timeout on a request.
func NewGETDomainsParamsWithTimeout(timeout time.Duration) *GETDomainsParams {
	return &GETDomainsParams{
		timeout: timeout,
	}
}

// NewGETDomainsParamsWithContext creates a new GETDomainsParams object
// with the ability to set a context for a request.
func NewGETDomainsParamsWithContext(ctx context.Context) *GETDomainsParams {
	return &GETDomainsParams{
		Context: ctx,
	}
}

// NewGETDomainsParamsWithHTTPClient creates a new GETDomainsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGETDomainsParamsWithHTTPClient(client *http.Client) *GETDomainsParams {
	return &GETDomainsParams{
		HTTPClient: client,
	}
}

/*
GETDomainsParams contains all the parameters to send to the API endpoint

	for the get domains operation.

	Typically these are written to a http.Request.
*/
type GETDomainsParams struct {

	/* Type.

	   The type of the domain
	*/
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get domains params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GETDomainsParams) WithDefaults() *GETDomainsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get domains params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GETDomainsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get domains params
func (o *GETDomainsParams) WithTimeout(timeout time.Duration) *GETDomainsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get domains params
func (o *GETDomainsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get domains params
func (o *GETDomainsParams) WithContext(ctx context.Context) *GETDomainsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get domains params
func (o *GETDomainsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get domains params
func (o *GETDomainsParams) WithHTTPClient(client *http.Client) *GETDomainsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get domains params
func (o *GETDomainsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithType adds the typeVar to the get domains params
func (o *GETDomainsParams) WithType(typeVar *string) *GETDomainsParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get domains params
func (o *GETDomainsParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GETDomainsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Type != nil {

		// query param type
		var qrType string

		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {

			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
