// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetClusterCriterionParams creates a new GetClusterCriterionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetClusterCriterionParams() *GetClusterCriterionParams {
	return &GetClusterCriterionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetClusterCriterionParamsWithTimeout creates a new GetClusterCriterionParams object
// with the ability to set a timeout on a request.
func NewGetClusterCriterionParamsWithTimeout(timeout time.Duration) *GetClusterCriterionParams {
	return &GetClusterCriterionParams{
		timeout: timeout,
	}
}

// NewGetClusterCriterionParamsWithContext creates a new GetClusterCriterionParams object
// with the ability to set a context for a request.
func NewGetClusterCriterionParamsWithContext(ctx context.Context) *GetClusterCriterionParams {
	return &GetClusterCriterionParams{
		Context: ctx,
	}
}

// NewGetClusterCriterionParamsWithHTTPClient creates a new GetClusterCriterionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetClusterCriterionParamsWithHTTPClient(client *http.Client) *GetClusterCriterionParams {
	return &GetClusterCriterionParams{
		HTTPClient: client,
	}
}

/*
GetClusterCriterionParams contains all the parameters to send to the API endpoint

	for the get cluster criterion operation.

	Typically these are written to a http.Request.
*/
type GetClusterCriterionParams struct {

	/* DomainID.

	   Domain ID
	*/
	DomainID string

	/* Name.

	   Criteria Name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get cluster criterion params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClusterCriterionParams) WithDefaults() *GetClusterCriterionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get cluster criterion params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClusterCriterionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get cluster criterion params
func (o *GetClusterCriterionParams) WithTimeout(timeout time.Duration) *GetClusterCriterionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cluster criterion params
func (o *GetClusterCriterionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cluster criterion params
func (o *GetClusterCriterionParams) WithContext(ctx context.Context) *GetClusterCriterionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cluster criterion params
func (o *GetClusterCriterionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cluster criterion params
func (o *GetClusterCriterionParams) WithHTTPClient(client *http.Client) *GetClusterCriterionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cluster criterion params
func (o *GetClusterCriterionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomainID adds the domainID to the get cluster criterion params
func (o *GetClusterCriterionParams) WithDomainID(domainID string) *GetClusterCriterionParams {
	o.SetDomainID(domainID)
	return o
}

// SetDomainID adds the domainId to the get cluster criterion params
func (o *GetClusterCriterionParams) SetDomainID(domainID string) {
	o.DomainID = domainID
}

// WithName adds the name to the get cluster criterion params
func (o *GetClusterCriterionParams) WithName(name string) *GetClusterCriterionParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get cluster criterion params
func (o *GetClusterCriterionParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetClusterCriterionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param domainId
	if err := r.SetPathParam("domainId", o.DomainID); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
