// Code generated by go-swagger; DO NOT EDIT.

// Copyright © 2023 VMware, Inc. All Rights Reserved.
// Code licenced under: BSD-2

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vcf-sdk-go/models"
)

// GETTagsAssignedToDomainsReader is a Reader for the GETTagsAssignedToDomains structure.
type GETTagsAssignedToDomainsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETTagsAssignedToDomainsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGETTagsAssignedToDomainsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGETTagsAssignedToDomainsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGETTagsAssignedToDomainsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGETTagsAssignedToDomainsOK creates a GETTagsAssignedToDomainsOK with default headers values
func NewGETTagsAssignedToDomainsOK() *GETTagsAssignedToDomainsOK {
	return &GETTagsAssignedToDomainsOK{}
}

/*
GETTagsAssignedToDomainsOK describes a response with status code 200, with default header values.

Ok
*/
type GETTagsAssignedToDomainsOK struct {
	Payload *models.PageOfTagsForResource
}

// IsSuccess returns true when this get tags assigned to domains o k response has a 2xx status code
func (o *GETTagsAssignedToDomainsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get tags assigned to domains o k response has a 3xx status code
func (o *GETTagsAssignedToDomainsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get tags assigned to domains o k response has a 4xx status code
func (o *GETTagsAssignedToDomainsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get tags assigned to domains o k response has a 5xx status code
func (o *GETTagsAssignedToDomainsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get tags assigned to domains o k response a status code equal to that given
func (o *GETTagsAssignedToDomainsOK) IsCode(code int) bool {
	return code == 200
}

func (o *GETTagsAssignedToDomainsOK) Error() string {
	return fmt.Sprintf("[GET /v1/domains/tags][%d] getTagsAssignedToDomainsOK  %+v", 200, o.Payload)
}

func (o *GETTagsAssignedToDomainsOK) String() string {
	return fmt.Sprintf("[GET /v1/domains/tags][%d] getTagsAssignedToDomainsOK  %+v", 200, o.Payload)
}

func (o *GETTagsAssignedToDomainsOK) GetPayload() *models.PageOfTagsForResource {
	return o.Payload
}

func (o *GETTagsAssignedToDomainsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PageOfTagsForResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETTagsAssignedToDomainsBadRequest creates a GETTagsAssignedToDomainsBadRequest with default headers values
func NewGETTagsAssignedToDomainsBadRequest() *GETTagsAssignedToDomainsBadRequest {
	return &GETTagsAssignedToDomainsBadRequest{}
}

/*
GETTagsAssignedToDomainsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GETTagsAssignedToDomainsBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get tags assigned to domains bad request response has a 2xx status code
func (o *GETTagsAssignedToDomainsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get tags assigned to domains bad request response has a 3xx status code
func (o *GETTagsAssignedToDomainsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get tags assigned to domains bad request response has a 4xx status code
func (o *GETTagsAssignedToDomainsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get tags assigned to domains bad request response has a 5xx status code
func (o *GETTagsAssignedToDomainsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get tags assigned to domains bad request response a status code equal to that given
func (o *GETTagsAssignedToDomainsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GETTagsAssignedToDomainsBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/domains/tags][%d] getTagsAssignedToDomainsBadRequest  %+v", 400, o.Payload)
}

func (o *GETTagsAssignedToDomainsBadRequest) String() string {
	return fmt.Sprintf("[GET /v1/domains/tags][%d] getTagsAssignedToDomainsBadRequest  %+v", 400, o.Payload)
}

func (o *GETTagsAssignedToDomainsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GETTagsAssignedToDomainsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETTagsAssignedToDomainsInternalServerError creates a GETTagsAssignedToDomainsInternalServerError with default headers values
func NewGETTagsAssignedToDomainsInternalServerError() *GETTagsAssignedToDomainsInternalServerError {
	return &GETTagsAssignedToDomainsInternalServerError{}
}

/*
GETTagsAssignedToDomainsInternalServerError describes a response with status code 500, with default header values.

InternalServerError
*/
type GETTagsAssignedToDomainsInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get tags assigned to domains internal server error response has a 2xx status code
func (o *GETTagsAssignedToDomainsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get tags assigned to domains internal server error response has a 3xx status code
func (o *GETTagsAssignedToDomainsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get tags assigned to domains internal server error response has a 4xx status code
func (o *GETTagsAssignedToDomainsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get tags assigned to domains internal server error response has a 5xx status code
func (o *GETTagsAssignedToDomainsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get tags assigned to domains internal server error response a status code equal to that given
func (o *GETTagsAssignedToDomainsInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GETTagsAssignedToDomainsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/domains/tags][%d] getTagsAssignedToDomainsInternalServerError  %+v", 500, o.Payload)
}

func (o *GETTagsAssignedToDomainsInternalServerError) String() string {
	return fmt.Sprintf("[GET /v1/domains/tags][%d] getTagsAssignedToDomainsInternalServerError  %+v", 500, o.Payload)
}

func (o *GETTagsAssignedToDomainsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GETTagsAssignedToDomainsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
