// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"vcf-sdk-go/models"
)

// GetDomainsReader is a Reader for the GetDomains structure.
type GetDomainsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDomainsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDomainsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetDomainsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetDomainsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDomainsOK creates a GetDomainsOK with default headers values
func NewGetDomainsOK() *GetDomainsOK {
	return &GetDomainsOK{}
}

/*
GetDomainsOK describes a response with status code 200, with default header values.

Ok
*/
type GetDomainsOK struct {
	Payload *models.PageOfDomain
}

// IsSuccess returns true when this get domains o k response has a 2xx status code
func (o *GetDomainsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get domains o k response has a 3xx status code
func (o *GetDomainsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get domains o k response has a 4xx status code
func (o *GetDomainsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get domains o k response has a 5xx status code
func (o *GetDomainsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get domains o k response a status code equal to that given
func (o *GetDomainsOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetDomainsOK) Error() string {
	return fmt.Sprintf("[GET /v1/domains][%d] getDomainsOK  %+v", 200, o.Payload)
}

func (o *GetDomainsOK) String() string {
	return fmt.Sprintf("[GET /v1/domains][%d] getDomainsOK  %+v", 200, o.Payload)
}

func (o *GetDomainsOK) GetPayload() *models.PageOfDomain {
	return o.Payload
}

func (o *GetDomainsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PageOfDomain)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDomainsBadRequest creates a GetDomainsBadRequest with default headers values
func NewGetDomainsBadRequest() *GetDomainsBadRequest {
	return &GetDomainsBadRequest{}
}

/*
GetDomainsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetDomainsBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get domains bad request response has a 2xx status code
func (o *GetDomainsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get domains bad request response has a 3xx status code
func (o *GetDomainsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get domains bad request response has a 4xx status code
func (o *GetDomainsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get domains bad request response has a 5xx status code
func (o *GetDomainsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get domains bad request response a status code equal to that given
func (o *GetDomainsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GetDomainsBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/domains][%d] getDomainsBadRequest  %+v", 400, o.Payload)
}

func (o *GetDomainsBadRequest) String() string {
	return fmt.Sprintf("[GET /v1/domains][%d] getDomainsBadRequest  %+v", 400, o.Payload)
}

func (o *GetDomainsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDomainsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDomainsInternalServerError creates a GetDomainsInternalServerError with default headers values
func NewGetDomainsInternalServerError() *GetDomainsInternalServerError {
	return &GetDomainsInternalServerError{}
}

/*
GetDomainsInternalServerError describes a response with status code 500, with default header values.

InternalServerError
*/
type GetDomainsInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get domains internal server error response has a 2xx status code
func (o *GetDomainsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get domains internal server error response has a 3xx status code
func (o *GetDomainsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get domains internal server error response has a 4xx status code
func (o *GetDomainsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get domains internal server error response has a 5xx status code
func (o *GetDomainsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get domains internal server error response a status code equal to that given
func (o *GetDomainsInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetDomainsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/domains][%d] getDomainsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDomainsInternalServerError) String() string {
	return fmt.Sprintf("[GET /v1/domains][%d] getDomainsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDomainsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDomainsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
