// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 VMware, Inc.
// SPDX-License-Identifier: BSD-2-Clause

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vcf-sdk-go/models"
)

// NewValidateDomainCreationSpecParams creates a new ValidateDomainCreationSpecParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewValidateDomainCreationSpecParams() *ValidateDomainCreationSpecParams {
	return &ValidateDomainCreationSpecParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewValidateDomainCreationSpecParamsWithTimeout creates a new ValidateDomainCreationSpecParams object
// with the ability to set a timeout on a request.
func NewValidateDomainCreationSpecParamsWithTimeout(timeout time.Duration) *ValidateDomainCreationSpecParams {
	return &ValidateDomainCreationSpecParams{
		timeout: timeout,
	}
}

// NewValidateDomainCreationSpecParamsWithContext creates a new ValidateDomainCreationSpecParams object
// with the ability to set a context for a request.
func NewValidateDomainCreationSpecParamsWithContext(ctx context.Context) *ValidateDomainCreationSpecParams {
	return &ValidateDomainCreationSpecParams{
		Context: ctx,
	}
}

// NewValidateDomainCreationSpecParamsWithHTTPClient creates a new ValidateDomainCreationSpecParams object
// with the ability to set a custom HTTPClient for a request.
func NewValidateDomainCreationSpecParamsWithHTTPClient(client *http.Client) *ValidateDomainCreationSpecParams {
	return &ValidateDomainCreationSpecParams{
		HTTPClient: client,
	}
}

/*
ValidateDomainCreationSpecParams contains all the parameters to send to the API endpoint

	for the validate domain creation spec operation.

	Typically these are written to a http.Request.
*/
type ValidateDomainCreationSpecParams struct {

	/* DomainCreationSpec.

	   Domain Creation Spec
	*/
	DomainCreationSpec *models.DomainCreationSpec

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the validate domain creation spec params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ValidateDomainCreationSpecParams) WithDefaults() *ValidateDomainCreationSpecParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the validate domain creation spec params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ValidateDomainCreationSpecParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the validate domain creation spec params
func (o *ValidateDomainCreationSpecParams) WithTimeout(timeout time.Duration) *ValidateDomainCreationSpecParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the validate domain creation spec params
func (o *ValidateDomainCreationSpecParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the validate domain creation spec params
func (o *ValidateDomainCreationSpecParams) WithContext(ctx context.Context) *ValidateDomainCreationSpecParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the validate domain creation spec params
func (o *ValidateDomainCreationSpecParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the validate domain creation spec params
func (o *ValidateDomainCreationSpecParams) WithHTTPClient(client *http.Client) *ValidateDomainCreationSpecParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the validate domain creation spec params
func (o *ValidateDomainCreationSpecParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomainCreationSpec adds the domainCreationSpec to the validate domain creation spec params
func (o *ValidateDomainCreationSpecParams) WithDomainCreationSpec(domainCreationSpec *models.DomainCreationSpec) *ValidateDomainCreationSpecParams {
	o.SetDomainCreationSpec(domainCreationSpec)
	return o
}

// SetDomainCreationSpec adds the domainCreationSpec to the validate domain creation spec params
func (o *ValidateDomainCreationSpecParams) SetDomainCreationSpec(domainCreationSpec *models.DomainCreationSpec) {
	o.DomainCreationSpec = domainCreationSpec
}

// WriteToRequest writes these params to a swagger request
func (o *ValidateDomainCreationSpecParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.DomainCreationSpec != nil {
		if err := r.SetBodyParam(o.DomainCreationSpec); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
