// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 VMware, Inc.
// SPDX-License-Identifier: BSD-2-Clause

package sddc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRetrieveSDDCParams creates a new RetrieveSDDCParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRetrieveSDDCParams() *RetrieveSDDCParams {
	return &RetrieveSDDCParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRetrieveSDDCParamsWithTimeout creates a new RetrieveSDDCParams object
// with the ability to set a timeout on a request.
func NewRetrieveSDDCParamsWithTimeout(timeout time.Duration) *RetrieveSDDCParams {
	return &RetrieveSDDCParams{
		timeout: timeout,
	}
}

// NewRetrieveSDDCParamsWithContext creates a new RetrieveSDDCParams object
// with the ability to set a context for a request.
func NewRetrieveSDDCParamsWithContext(ctx context.Context) *RetrieveSDDCParams {
	return &RetrieveSDDCParams{
		Context: ctx,
	}
}

// NewRetrieveSDDCParamsWithHTTPClient creates a new RetrieveSDDCParams object
// with the ability to set a custom HTTPClient for a request.
func NewRetrieveSDDCParamsWithHTTPClient(client *http.Client) *RetrieveSDDCParams {
	return &RetrieveSDDCParams{
		HTTPClient: client,
	}
}

/*
RetrieveSDDCParams contains all the parameters to send to the API endpoint

	for the retrieve SDDC operation.

	Typically these are written to a http.Request.
*/
type RetrieveSDDCParams struct {

	/* ID.

	   SDDC ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the retrieve SDDC params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RetrieveSDDCParams) WithDefaults() *RetrieveSDDCParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the retrieve SDDC params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RetrieveSDDCParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the retrieve SDDC params
func (o *RetrieveSDDCParams) WithTimeout(timeout time.Duration) *RetrieveSDDCParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the retrieve SDDC params
func (o *RetrieveSDDCParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the retrieve SDDC params
func (o *RetrieveSDDCParams) WithContext(ctx context.Context) *RetrieveSDDCParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the retrieve SDDC params
func (o *RetrieveSDDCParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the retrieve SDDC params
func (o *RetrieveSDDCParams) WithHTTPClient(client *http.Client) *RetrieveSDDCParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the retrieve SDDC params
func (o *RetrieveSDDCParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the retrieve SDDC params
func (o *RetrieveSDDCParams) WithID(id string) *RetrieveSDDCParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the retrieve SDDC params
func (o *RetrieveSDDCParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *RetrieveSDDCParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
