// Code generated by go-swagger; DO NOT EDIT.

// Copyright © 2023 VMware, Inc. All Rights Reserved.
// Code licenced under: BSD-2

package sddc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new sddc API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for sddc API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	ConvertToJSONSpec(params *ConvertToJSONSpecParams, opts ...ClientOption) (*ConvertToJSONSpecOK, error)

	CreateSDDC(params *CreateSDDCParams, opts ...ClientOption) (*CreateSDDCOK, *CreateSDDCAccepted, error)

	GETAllSDDCValidations(params *GETAllSDDCValidationsParams, opts ...ClientOption) (*GETAllSDDCValidationsOK, error)

	GETBringupDetailReport(params *GETBringupDetailReportParams, opts ...ClientOption) (*GETBringupDetailReportOK, *GETBringupDetailReportNoContent, error)

	GETBringupInfo(params *GETBringupInfoParams, opts ...ClientOption) (*GETBringupInfoOK, error)

	GETBringupValidationReport(params *GETBringupValidationReportParams, opts ...ClientOption) (*GETBringupValidationReportOK, error)

	GETSDDCManagerInfo(params *GETSDDCManagerInfoParams, opts ...ClientOption) (*GETSDDCManagerInfoOK, error)

	GETSDDCValidation(params *GETSDDCValidationParams, opts ...ClientOption) (*GETSDDCValidationOK, error)

	RetrieveAllSddcs(params *RetrieveAllSddcsParams, opts ...ClientOption) (*RetrieveAllSddcsOK, error)

	RetrieveSDDC(params *RetrieveSDDCParams, opts ...ClientOption) (*RetrieveSDDCOK, error)

	RetrySDDC(params *RetrySDDCParams, opts ...ClientOption) (*RetrySDDCOK, *RetrySDDCAccepted, error)

	RetrySDDCValidation(params *RetrySDDCValidationParams, opts ...ClientOption) (*RetrySDDCValidationOK, error)

	ValidateSDDCSpec(params *ValidateSDDCSpecParams, opts ...ClientOption) (*ValidateSDDCSpecOK, *ValidateSDDCSpecAccepted, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
ConvertToJSONSpec converts SDDC specification Json excel file

SDDC specification incorporates all the client inputs regarding VMW component parameters constituting the SDDC: NTP, DNS spec, ESXi, VC, VSAN, NSX spec et al.
*/
func (a *Client) ConvertToJSONSpec(params *ConvertToJSONSpecParams, opts ...ClientOption) (*ConvertToJSONSpecOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewConvertToJSONSpecParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "convertToJsonSpec",
		Method:             "POST",
		PathPattern:        "/v1/system/sddc-spec-converter",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"multipart/form-data"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ConvertToJSONSpecReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ConvertToJSONSpecOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for convertToJsonSpec: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
CreateSDDC creates SDDC
*/
func (a *Client) CreateSDDC(params *CreateSDDCParams, opts ...ClientOption) (*CreateSDDCOK, *CreateSDDCAccepted, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateSDDCParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "createSddc",
		Method:             "POST",
		PathPattern:        "/v1/sddcs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateSDDCReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *CreateSDDCOK:
		return value, nil, nil
	case *CreateSDDCAccepted:
		return nil, value, nil
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for sddc: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GETAllSDDCValidations Gets all SDDC specification validations
*/
func (a *Client) GETAllSDDCValidations(params *GETAllSDDCValidationsParams, opts ...ClientOption) (*GETAllSDDCValidationsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGETAllSDDCValidationsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getAllSddcValidations",
		Method:             "GET",
		PathPattern:        "/v1/sddcs/validations",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GETAllSDDCValidationsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GETAllSDDCValidationsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getAllSddcValidations: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GETBringupDetailReport Gets SDDC report by ID

Returns the bringup report. Reports are generated in PDF and CSV formats.
*/
func (a *Client) GETBringupDetailReport(params *GETBringupDetailReportParams, opts ...ClientOption) (*GETBringupDetailReportOK, *GETBringupDetailReportNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGETBringupDetailReportParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getBringupDetailReport",
		Method:             "GET",
		PathPattern:        "/v1/sddcs/{id}/detail-report",
		ProducesMediaTypes: []string{"application/pdf", "text/csv"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GETBringupDetailReportReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *GETBringupDetailReportOK:
		return value, nil, nil
	case *GETBringupDetailReportNoContent:
		return nil, value, nil
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for sddc: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GETBringupInfo Gets bringup info

GET Method to retrieve information about Bringup app
*/
func (a *Client) GETBringupInfo(params *GETBringupInfoParams, opts ...ClientOption) (*GETBringupInfoOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGETBringupInfoParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getBringupInfo",
		Method:             "GET",
		PathPattern:        "/v1/sddcs/about",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GETBringupInfoReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GETBringupInfoOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getBringupInfo: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GETBringupValidationReport Gets validation report by ID

Returns the bringup report for a validation. Reports are generated in PDF format.
*/
func (a *Client) GETBringupValidationReport(params *GETBringupValidationReportParams, opts ...ClientOption) (*GETBringupValidationReportOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGETBringupValidationReportParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getBringupValidationReport",
		Method:             "GET",
		PathPattern:        "/v1/sddcs/validations/{validationId}/report",
		ProducesMediaTypes: []string{"application/pdf"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GETBringupValidationReportReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GETBringupValidationReportOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getBringupValidationReport: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GETSDDCManagerInfo retrieves SDDC manager VM details

Retrieves the details of SDDC Manager VM
*/
func (a *Client) GETSDDCManagerInfo(params *GETSDDCManagerInfoParams, opts ...ClientOption) (*GETSDDCManagerInfoOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGETSDDCManagerInfoParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getSddcManagerInfo",
		Method:             "GET",
		PathPattern:        "/v1/sddcs/{id}/sddc-manager",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GETSDDCManagerInfoReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GETSDDCManagerInfoOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getSddcManagerInfo: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GETSDDCValidation Gets SDDC specification validation status by ID
*/
func (a *Client) GETSDDCValidation(params *GETSDDCValidationParams, opts ...ClientOption) (*GETSDDCValidationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGETSDDCValidationParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getSddcValidation",
		Method:             "GET",
		PathPattern:        "/v1/sddcs/validations/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GETSDDCValidationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GETSDDCValidationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getSddcValidation: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
RetrieveAllSddcs retrieves all s d d cs
*/
func (a *Client) RetrieveAllSddcs(params *RetrieveAllSddcsParams, opts ...ClientOption) (*RetrieveAllSddcsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRetrieveAllSddcsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "retrieveAllSddcs",
		Method:             "GET",
		PathPattern:        "/v1/sddcs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RetrieveAllSddcsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*RetrieveAllSddcsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for retrieveAllSddcs: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
RetrieveSDDC retrieves a SDDC
*/
func (a *Client) RetrieveSDDC(params *RetrieveSDDCParams, opts ...ClientOption) (*RetrieveSDDCOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRetrieveSDDCParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "retrieveSDDC",
		Method:             "GET",
		PathPattern:        "/v1/sddcs/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RetrieveSDDCReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*RetrieveSDDCOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for retrieveSDDC: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
RetrySDDC retries failed SDDC creation
*/
func (a *Client) RetrySDDC(params *RetrySDDCParams, opts ...ClientOption) (*RetrySDDCOK, *RetrySDDCAccepted, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRetrySDDCParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "retrySddc",
		Method:             "PATCH",
		PathPattern:        "/v1/sddcs/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RetrySDDCReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *RetrySDDCOK:
		return value, nil, nil
	case *RetrySDDCAccepted:
		return nil, value, nil
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for sddc: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
RetrySDDCValidation retries SDDC validation

Retry a completed SDDC validation
*/
func (a *Client) RetrySDDCValidation(params *RetrySDDCValidationParams, opts ...ClientOption) (*RetrySDDCValidationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRetrySDDCValidationParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "retrySddcValidation",
		Method:             "PATCH",
		PathPattern:        "/v1/sddcs/validations/{id}",
		ProducesMediaTypes: []string{"*/*"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RetrySDDCValidationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*RetrySDDCValidationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for retrySddcValidation: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ValidateSDDCSpec validates SDDC specification before creation

SDDC specification incorporates all the client inputs regarding VMW component parameters constituting the SDDC: NTP, DNS spec, ESXi, VC, VSAN, NSX spec et al.
*/
func (a *Client) ValidateSDDCSpec(params *ValidateSDDCSpecParams, opts ...ClientOption) (*ValidateSDDCSpecOK, *ValidateSDDCSpecAccepted, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewValidateSDDCSpecParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "validateSddcSpec",
		Method:             "POST",
		PathPattern:        "/v1/sddcs/validations",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ValidateSDDCSpecReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *ValidateSDDCSpecOK:
		return value, nil, nil
	case *ValidateSDDCSpecAccepted:
		return nil, value, nil
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for sddc: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
