// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 VMware, Inc.
// SPDX-License-Identifier: BSD-2-Clause

package credentials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vcf-sdk-go/models"
)

// NewGetPasswordExpirationParams creates a new GetPasswordExpirationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPasswordExpirationParams() *GetPasswordExpirationParams {
	return &GetPasswordExpirationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPasswordExpirationParamsWithTimeout creates a new GetPasswordExpirationParams object
// with the ability to set a timeout on a request.
func NewGetPasswordExpirationParamsWithTimeout(timeout time.Duration) *GetPasswordExpirationParams {
	return &GetPasswordExpirationParams{
		timeout: timeout,
	}
}

// NewGetPasswordExpirationParamsWithContext creates a new GetPasswordExpirationParams object
// with the ability to set a context for a request.
func NewGetPasswordExpirationParamsWithContext(ctx context.Context) *GetPasswordExpirationParams {
	return &GetPasswordExpirationParams{
		Context: ctx,
	}
}

// NewGetPasswordExpirationParamsWithHTTPClient creates a new GetPasswordExpirationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPasswordExpirationParamsWithHTTPClient(client *http.Client) *GetPasswordExpirationParams {
	return &GetPasswordExpirationParams{
		HTTPClient: client,
	}
}

/*
GetPasswordExpirationParams contains all the parameters to send to the API endpoint

	for the get password expiration operation.

	Typically these are written to a http.Request.
*/
type GetPasswordExpirationParams struct {

	/* CredentialsExpirationSpec.

	   credentialsExpirationSpec
	*/
	CredentialsExpirationSpec *models.CredentialsExpirationSpec

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get password expiration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPasswordExpirationParams) WithDefaults() *GetPasswordExpirationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get password expiration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPasswordExpirationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get password expiration params
func (o *GetPasswordExpirationParams) WithTimeout(timeout time.Duration) *GetPasswordExpirationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get password expiration params
func (o *GetPasswordExpirationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get password expiration params
func (o *GetPasswordExpirationParams) WithContext(ctx context.Context) *GetPasswordExpirationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get password expiration params
func (o *GetPasswordExpirationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get password expiration params
func (o *GetPasswordExpirationParams) WithHTTPClient(client *http.Client) *GetPasswordExpirationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get password expiration params
func (o *GetPasswordExpirationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCredentialsExpirationSpec adds the credentialsExpirationSpec to the get password expiration params
func (o *GetPasswordExpirationParams) WithCredentialsExpirationSpec(credentialsExpirationSpec *models.CredentialsExpirationSpec) *GetPasswordExpirationParams {
	o.SetCredentialsExpirationSpec(credentialsExpirationSpec)
	return o
}

// SetCredentialsExpirationSpec adds the credentialsExpirationSpec to the get password expiration params
func (o *GetPasswordExpirationParams) SetCredentialsExpirationSpec(credentialsExpirationSpec *models.CredentialsExpirationSpec) {
	o.CredentialsExpirationSpec = credentialsExpirationSpec
}

// WriteToRequest writes these params to a swagger request
func (o *GetPasswordExpirationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.CredentialsExpirationSpec != nil {
		if err := r.SetBodyParam(o.CredentialsExpirationSpec); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
