// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 VMware, Inc.
// SPDX-License-Identifier: BSD-2-Clause

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGETRolesParams creates a new GETRolesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGETRolesParams() *GETRolesParams {
	return &GETRolesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGETRolesParamsWithTimeout creates a new GETRolesParams object
// with the ability to set a timeout on a request.
func NewGETRolesParamsWithTimeout(timeout time.Duration) *GETRolesParams {
	return &GETRolesParams{
		timeout: timeout,
	}
}

// NewGETRolesParamsWithContext creates a new GETRolesParams object
// with the ability to set a context for a request.
func NewGETRolesParamsWithContext(ctx context.Context) *GETRolesParams {
	return &GETRolesParams{
		Context: ctx,
	}
}

// NewGETRolesParamsWithHTTPClient creates a new GETRolesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGETRolesParamsWithHTTPClient(client *http.Client) *GETRolesParams {
	return &GETRolesParams{
		HTTPClient: client,
	}
}

/*
GETRolesParams contains all the parameters to send to the API endpoint

	for the get roles operation.

	Typically these are written to a http.Request.
*/
type GETRolesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get roles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GETRolesParams) WithDefaults() *GETRolesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get roles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GETRolesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get roles params
func (o *GETRolesParams) WithTimeout(timeout time.Duration) *GETRolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get roles params
func (o *GETRolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get roles params
func (o *GETRolesParams) WithContext(ctx context.Context) *GETRolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get roles params
func (o *GETRolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get roles params
func (o *GETRolesParams) WithHTTPClient(client *http.Client) *GETRolesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get roles params
func (o *GETRolesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GETRolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
