// Code generated by go-swagger; DO NOT EDIT.

// Copyright © 2023 VMware, Inc. All Rights Reserved.
// Code licenced under: BSD-2

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGETSSODomainEntitiesParams creates a new GETSSODomainEntitiesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGETSSODomainEntitiesParams() *GETSSODomainEntitiesParams {
	return &GETSSODomainEntitiesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGETSSODomainEntitiesParamsWithTimeout creates a new GETSSODomainEntitiesParams object
// with the ability to set a timeout on a request.
func NewGETSSODomainEntitiesParamsWithTimeout(timeout time.Duration) *GETSSODomainEntitiesParams {
	return &GETSSODomainEntitiesParams{
		timeout: timeout,
	}
}

// NewGETSSODomainEntitiesParamsWithContext creates a new GETSSODomainEntitiesParams object
// with the ability to set a context for a request.
func NewGETSSODomainEntitiesParamsWithContext(ctx context.Context) *GETSSODomainEntitiesParams {
	return &GETSSODomainEntitiesParams{
		Context: ctx,
	}
}

// NewGETSSODomainEntitiesParamsWithHTTPClient creates a new GETSSODomainEntitiesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGETSSODomainEntitiesParamsWithHTTPClient(client *http.Client) *GETSSODomainEntitiesParams {
	return &GETSSODomainEntitiesParams{
		HTTPClient: client,
	}
}

/*
GETSSODomainEntitiesParams contains all the parameters to send to the API endpoint

	for the get s s o domain entities operation.

	Typically these are written to a http.Request.
*/
type GETSSODomainEntitiesParams struct {

	/* SsoDomain.

	   SSO Domain Name
	*/
	SsoDomain string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get s s o domain entities params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GETSSODomainEntitiesParams) WithDefaults() *GETSSODomainEntitiesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get s s o domain entities params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GETSSODomainEntitiesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get s s o domain entities params
func (o *GETSSODomainEntitiesParams) WithTimeout(timeout time.Duration) *GETSSODomainEntitiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get s s o domain entities params
func (o *GETSSODomainEntitiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get s s o domain entities params
func (o *GETSSODomainEntitiesParams) WithContext(ctx context.Context) *GETSSODomainEntitiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get s s o domain entities params
func (o *GETSSODomainEntitiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get s s o domain entities params
func (o *GETSSODomainEntitiesParams) WithHTTPClient(client *http.Client) *GETSSODomainEntitiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get s s o domain entities params
func (o *GETSSODomainEntitiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSsoDomain adds the ssoDomain to the get s s o domain entities params
func (o *GETSSODomainEntitiesParams) WithSsoDomain(ssoDomain string) *GETSSODomainEntitiesParams {
	o.SetSsoDomain(ssoDomain)
	return o
}

// SetSsoDomain adds the ssoDomain to the get s s o domain entities params
func (o *GETSSODomainEntitiesParams) SetSsoDomain(ssoDomain string) {
	o.SsoDomain = ssoDomain
}

// WriteToRequest writes these params to a swagger request
func (o *GETSSODomainEntitiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param sso-domain
	if err := r.SetPathParam("sso-domain", o.SsoDomain); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
