// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 VMware, Inc.
// SPDX-License-Identifier: BSD-2-Clause

package vrli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetIntegratedDomains1Params creates a new GetIntegratedDomains1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetIntegratedDomains1Params() *GetIntegratedDomains1Params {
	return &GetIntegratedDomains1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetIntegratedDomains1ParamsWithTimeout creates a new GetIntegratedDomains1Params object
// with the ability to set a timeout on a request.
func NewGetIntegratedDomains1ParamsWithTimeout(timeout time.Duration) *GetIntegratedDomains1Params {
	return &GetIntegratedDomains1Params{
		timeout: timeout,
	}
}

// NewGetIntegratedDomains1ParamsWithContext creates a new GetIntegratedDomains1Params object
// with the ability to set a context for a request.
func NewGetIntegratedDomains1ParamsWithContext(ctx context.Context) *GetIntegratedDomains1Params {
	return &GetIntegratedDomains1Params{
		Context: ctx,
	}
}

// NewGetIntegratedDomains1ParamsWithHTTPClient creates a new GetIntegratedDomains1Params object
// with the ability to set a custom HTTPClient for a request.
func NewGetIntegratedDomains1ParamsWithHTTPClient(client *http.Client) *GetIntegratedDomains1Params {
	return &GetIntegratedDomains1Params{
		HTTPClient: client,
	}
}

/*
GetIntegratedDomains1Params contains all the parameters to send to the API endpoint

	for the get integrated domains 1 operation.

	Typically these are written to a http.Request.
*/
type GetIntegratedDomains1Params struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get integrated domains 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIntegratedDomains1Params) WithDefaults() *GetIntegratedDomains1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get integrated domains 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIntegratedDomains1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get integrated domains 1 params
func (o *GetIntegratedDomains1Params) WithTimeout(timeout time.Duration) *GetIntegratedDomains1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get integrated domains 1 params
func (o *GetIntegratedDomains1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get integrated domains 1 params
func (o *GetIntegratedDomains1Params) WithContext(ctx context.Context) *GetIntegratedDomains1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get integrated domains 1 params
func (o *GetIntegratedDomains1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get integrated domains 1 params
func (o *GetIntegratedDomains1Params) WithHTTPClient(client *http.Client) *GetIntegratedDomains1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get integrated domains 1 params
func (o *GetIntegratedDomains1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetIntegratedDomains1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
