// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 VMware, Inc.
// SPDX-License-Identifier: BSD-2-Clause

package upgrades

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStartUpgradePrecheckParams creates a new StartUpgradePrecheckParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStartUpgradePrecheckParams() *StartUpgradePrecheckParams {
	return &StartUpgradePrecheckParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStartUpgradePrecheckParamsWithTimeout creates a new StartUpgradePrecheckParams object
// with the ability to set a timeout on a request.
func NewStartUpgradePrecheckParamsWithTimeout(timeout time.Duration) *StartUpgradePrecheckParams {
	return &StartUpgradePrecheckParams{
		timeout: timeout,
	}
}

// NewStartUpgradePrecheckParamsWithContext creates a new StartUpgradePrecheckParams object
// with the ability to set a context for a request.
func NewStartUpgradePrecheckParamsWithContext(ctx context.Context) *StartUpgradePrecheckParams {
	return &StartUpgradePrecheckParams{
		Context: ctx,
	}
}

// NewStartUpgradePrecheckParamsWithHTTPClient creates a new StartUpgradePrecheckParams object
// with the ability to set a custom HTTPClient for a request.
func NewStartUpgradePrecheckParamsWithHTTPClient(client *http.Client) *StartUpgradePrecheckParams {
	return &StartUpgradePrecheckParams{
		HTTPClient: client,
	}
}

/*
StartUpgradePrecheckParams contains all the parameters to send to the API endpoint

	for the start upgrade precheck operation.

	Typically these are written to a http.Request.
*/
type StartUpgradePrecheckParams struct {

	/* UpgradeID.

	   upgradeId
	*/
	UpgradeID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the start upgrade precheck params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StartUpgradePrecheckParams) WithDefaults() *StartUpgradePrecheckParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the start upgrade precheck params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StartUpgradePrecheckParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the start upgrade precheck params
func (o *StartUpgradePrecheckParams) WithTimeout(timeout time.Duration) *StartUpgradePrecheckParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the start upgrade precheck params
func (o *StartUpgradePrecheckParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the start upgrade precheck params
func (o *StartUpgradePrecheckParams) WithContext(ctx context.Context) *StartUpgradePrecheckParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the start upgrade precheck params
func (o *StartUpgradePrecheckParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the start upgrade precheck params
func (o *StartUpgradePrecheckParams) WithHTTPClient(client *http.Client) *StartUpgradePrecheckParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the start upgrade precheck params
func (o *StartUpgradePrecheckParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUpgradeID adds the upgradeID to the start upgrade precheck params
func (o *StartUpgradePrecheckParams) WithUpgradeID(upgradeID string) *StartUpgradePrecheckParams {
	o.SetUpgradeID(upgradeID)
	return o
}

// SetUpgradeID adds the upgradeId to the start upgrade precheck params
func (o *StartUpgradePrecheckParams) SetUpgradeID(upgradeID string) {
	o.UpgradeID = upgradeID
}

// WriteToRequest writes these params to a swagger request
func (o *StartUpgradePrecheckParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param upgradeId
	if err := r.SetPathParam("upgradeId", o.UpgradeID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
