// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BaseAlias Base Alias representation
//
// swagger:model BaseAlias
type BaseAlias struct {

	// List of Alias versions
	// Required: true
	Aliases []string `json:"aliases"`

	// Base version
	// Required: true
	Version *string `json:"version"`
}

// Validate validates this base alias
func (m *BaseAlias) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAliases(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BaseAlias) validateAliases(formats strfmt.Registry) error {

	if err := validate.Required("aliases", "body", m.Aliases); err != nil {
		return err
	}

	return nil
}

func (m *BaseAlias) validateVersion(formats strfmt.Registry) error {

	if err := validate.Required("version", "body", m.Version); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this base alias based on context it is used
func (m *BaseAlias) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BaseAlias) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BaseAlias) UnmarshalBinary(b []byte) error {
	var res BaseAlias
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
