// Code generated by go-swagger; DO NOT EDIT.

// Copyright © 2023 VMware, Inc. All Rights Reserved.
// Code licenced under: BSD-2

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NSXTIPAddressPoolRange NSX-T IP address pool range representation
//
// swagger:model NsxtIpAddressPoolRange
type NSXTIPAddressPoolRange struct {

	// The end of the IP address range
	End string `json:"end,omitempty"`

	// The start of the IP address range
	Start string `json:"start,omitempty"`
}

// Validate validates this Nsxt Ip address pool range
func (m *NSXTIPAddressPoolRange) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this Nsxt Ip address pool range based on context it is used
func (m *NSXTIPAddressPoolRange) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NSXTIPAddressPoolRange) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NSXTIPAddressPoolRange) UnmarshalBinary(b []byte) error {
	var res NSXTIPAddressPoolRange
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
