// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 VMware, Inc.
// SPDX-License-Identifier: BSD-2-Clause

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NSXTIPAddressPoolValidationSpec Nsxt Ip address pool validation spec
//
// swagger:model NsxtIpAddressPoolValidationSpec
type NSXTIPAddressPoolValidationSpec struct {

	// ip address pool spec
	// Required: true
	IPAddressPoolSpec *IPAddressPoolSpec `json:"ipAddressPoolSpec"`

	// nsxt cluster Id
	// Required: true
	NSXTClusterID *string `json:"nsxtClusterId"`
}

// Validate validates this Nsxt Ip address pool validation spec
func (m *NSXTIPAddressPoolValidationSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIPAddressPoolSpec(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNSXTClusterID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NSXTIPAddressPoolValidationSpec) validateIPAddressPoolSpec(formats strfmt.Registry) error {

	if err := validate.Required("ipAddressPoolSpec", "body", m.IPAddressPoolSpec); err != nil {
		return err
	}

	if m.IPAddressPoolSpec != nil {
		if err := m.IPAddressPoolSpec.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ipAddressPoolSpec")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ipAddressPoolSpec")
			}
			return err
		}
	}

	return nil
}

func (m *NSXTIPAddressPoolValidationSpec) validateNSXTClusterID(formats strfmt.Registry) error {

	if err := validate.Required("nsxtClusterId", "body", m.NSXTClusterID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this Nsxt Ip address pool validation spec based on the context it is used
func (m *NSXTIPAddressPoolValidationSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateIPAddressPoolSpec(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NSXTIPAddressPoolValidationSpec) contextValidateIPAddressPoolSpec(ctx context.Context, formats strfmt.Registry) error {

	if m.IPAddressPoolSpec != nil {

		if err := m.IPAddressPoolSpec.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ipAddressPoolSpec")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ipAddressPoolSpec")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NSXTIPAddressPoolValidationSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NSXTIPAddressPoolValidationSpec) UnmarshalBinary(b []byte) error {
	var res NSXTIPAddressPoolValidationSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
