// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 VMware, Inc.
// SPDX-License-Identifier: BSD-2-Clause

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// QueryInfo Represents the query info.
//
// swagger:model QueryInfo
type QueryInfo struct {

	// completed
	Completed bool `json:"completed,omitempty"`

	// Error response if the query has failed
	ErrorResponse *Error `json:"errorResponse,omitempty"`

	// failure
	Failure bool `json:"failure,omitempty"`

	// processing
	Processing bool `json:"processing,omitempty"`

	// ID of the query to retrieve
	QueryID string `json:"queryId,omitempty"`

	// Status of the query
	Status string `json:"status,omitempty"`
}

// Validate validates this query info
func (m *QueryInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateErrorResponse(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QueryInfo) validateErrorResponse(formats strfmt.Registry) error {
	if swag.IsZero(m.ErrorResponse) { // not required
		return nil
	}

	if m.ErrorResponse != nil {
		if err := m.ErrorResponse.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("errorResponse")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("errorResponse")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this query info based on the context it is used
func (m *QueryInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateErrorResponse(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QueryInfo) contextValidateErrorResponse(ctx context.Context, formats strfmt.Registry) error {

	if m.ErrorResponse != nil {

		if swag.IsZero(m.ErrorResponse) { // not required
			return nil
		}

		if err := m.ErrorResponse.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("errorResponse")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("errorResponse")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *QueryInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QueryInfo) UnmarshalBinary(b []byte) error {
	var res QueryInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
