// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 VMware, Inc.
// SPDX-License-Identifier: BSD-2-Clause

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VxRailCustomArrayContext Contains the details of simple/complex custom attribute on an array item object.
//
// swagger:model VxRailCustomArrayContext
type VxRailCustomArrayContext struct {

	// Details that holds the mapping between the custom attributes to the array item
	ArrayAssociationContext *VxRailArrayAssociationContext `json:"arrayAssociationContext,omitempty"`

	// Collection of simple attributes that contains name, value and type for each attribute.
	SimpleAttributes []*VxRailContext `json:"simpleAttributes"`
}

// Validate validates this vx rail custom array context
func (m *VxRailCustomArrayContext) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateArrayAssociationContext(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSimpleAttributes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VxRailCustomArrayContext) validateArrayAssociationContext(formats strfmt.Registry) error {
	if swag.IsZero(m.ArrayAssociationContext) { // not required
		return nil
	}

	if m.ArrayAssociationContext != nil {
		if err := m.ArrayAssociationContext.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("arrayAssociationContext")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("arrayAssociationContext")
			}
			return err
		}
	}

	return nil
}

func (m *VxRailCustomArrayContext) validateSimpleAttributes(formats strfmt.Registry) error {
	if swag.IsZero(m.SimpleAttributes) { // not required
		return nil
	}

	for i := 0; i < len(m.SimpleAttributes); i++ {
		if swag.IsZero(m.SimpleAttributes[i]) { // not required
			continue
		}

		if m.SimpleAttributes[i] != nil {
			if err := m.SimpleAttributes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("simpleAttributes" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("simpleAttributes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this vx rail custom array context based on the context it is used
func (m *VxRailCustomArrayContext) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateArrayAssociationContext(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSimpleAttributes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VxRailCustomArrayContext) contextValidateArrayAssociationContext(ctx context.Context, formats strfmt.Registry) error {

	if m.ArrayAssociationContext != nil {

		if swag.IsZero(m.ArrayAssociationContext) { // not required
			return nil
		}

		if err := m.ArrayAssociationContext.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("arrayAssociationContext")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("arrayAssociationContext")
			}
			return err
		}
	}

	return nil
}

func (m *VxRailCustomArrayContext) contextValidateSimpleAttributes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SimpleAttributes); i++ {

		if m.SimpleAttributes[i] != nil {

			if swag.IsZero(m.SimpleAttributes[i]) { // not required
				return nil
			}

			if err := m.SimpleAttributes[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("simpleAttributes" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("simpleAttributes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *VxRailCustomArrayContext) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VxRailCustomArrayContext) UnmarshalBinary(b []byte) error {
	var res VxRailCustomArrayContext
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
