// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WitnessSpec Spec contains the Witness host parameters that are part of each stretched cluster
//
// swagger:model WitnessSpec
type WitnessSpec struct {

	// Management ip of the witness host
	// Required: true
	Fqdn *string `json:"fqdn"`

	// vSAN subnet cidr of the witness host
	// Required: true
	VsanCidr *string `json:"vsanCidr"`

	// vSAN IP of the witness host
	// Required: true
	VsanIP *string `json:"vsanIp"`
}

// Validate validates this witness spec
func (m *WitnessSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFqdn(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVsanCidr(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVsanIP(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WitnessSpec) validateFqdn(formats strfmt.Registry) error {

	if err := validate.Required("fqdn", "body", m.Fqdn); err != nil {
		return err
	}

	return nil
}

func (m *WitnessSpec) validateVsanCidr(formats strfmt.Registry) error {

	if err := validate.Required("vsanCidr", "body", m.VsanCidr); err != nil {
		return err
	}

	return nil
}

func (m *WitnessSpec) validateVsanIP(formats strfmt.Registry) error {

	if err := validate.Required("vsanIp", "body", m.VsanIP); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this witness spec based on context it is used
func (m *WitnessSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WitnessSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WitnessSpec) UnmarshalBinary(b []byte) error {
	var res WitnessSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
